/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package queries;

/**
 *
 * @author Jett
 */
public class Education_Location extends javax.swing.JPanel {

    /**
     * Creates new form Person_Income_Location
     */
    
    private Age age;
    private Location location;
    private Edu edu;
    private Income income;
    public Education_Location() {
        initComponents();
        this.age = new Age();
        this.location = new Location();
        this.edu = new Edu();
        this.income = new Income();
        add(this.income);
        add(this.age);
        add(this.location);
        add(this.edu);
        
    }
    
    public Income getIncome(){
        return income;
    }
    
    public Age getAge(){
        return this.age;
    }
    
    public Location getLoc(){
        return this.location;
    }
    
    public Edu getEdu(){
        return this.edu;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
