/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package queries;

import java.util.ArrayList;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;

/**
 *
 * @author Jett
 */
public class Location extends javax.swing.JPanel {

    /**
     * Creates new form Location
     */
    public Location() {
        initComponents();
        province.setSelected(true);
        
    }

    public String getSelected(){
        
        String s = getSelectedButtonText(locations);
        
        return s;
    }
    
    
    public ArrayList<String> getLocations(){
        ArrayList<String> slist =new ArrayList<>();
        String selected = getSelected();

        switch(selected){
            case "Purok":slist.add(0,"purok");
            
            case "Barangay":slist.add(0,"brgy");
            
            case "Zone":slist.add(0,"zone");
            
            case "Municipality":slist.add(0,"mun");
            
            case "Province":slist.add(0,"place_name");
        }
       return slist;
    }
    

    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        locations = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        mun = new javax.swing.JRadioButton();
        zone = new javax.swing.JRadioButton();
        brgy = new javax.swing.JRadioButton();
        purok = new javax.swing.JRadioButton();
        province = new javax.swing.JRadioButton();

        jLabel1.setText("Location Level    ");

        locations.add(mun);
        mun.setText("Municipality");

        locations.add(zone);
        zone.setText("Zone");

        locations.add(brgy);
        brgy.setText("Barangay");

        locations.add(purok);
        purok.setText("Purok");

        locations.add(province);
        province.setText("Province");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(province)
                    .addComponent(purok)
                    .addComponent(brgy)
                    .addComponent(zone)
                    .addComponent(mun)
                    .addComponent(jLabel1))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(province)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brgy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(purok)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton brgy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.ButtonGroup locations;
    private javax.swing.JRadioButton mun;
    private javax.swing.JRadioButton province;
    private javax.swing.JRadioButton purok;
    private javax.swing.JRadioButton zone;
    // End of variables declaration//GEN-END:variables
}
